[pr_reviewer]
extra_instructions = """
이 PR은 『컴퓨터 밑바닥의 비밀』 책의 과제를 기반으로 한 구현입니다.
컴퓨터 과학 개념을 코드로 직접 구현하며 학습하는 목적이며, 아래 기준을 중심으로 리뷰를 요청합니다:

1. 구현이 해당 CS 개념(ALU, 어셈블러, 인터프리터 등)에 충실한지
2. 코드가 구조적으로 잘 나뉘고, 확장 가능하도록 설계되어 있는지
3. UI와 상호작용이 직관적이며, 기능적으로 완전한지
4. 코드 스타일과 네이밍도 함께 리뷰하되, 위 기준보다 우선순위는 낮게 설정해 주세요.
"""